name: Deploy gh-pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - run: npm run build
    - uses: JamesIves/github-pages-deploy-action@v4
      with:
        branch: gh-pages
        folder: build
        clean: true
